version: "3.9"

services:
  backend:
    image: serversideup/php:8.2-fpm-nginx
    container_name: sistema_gestao_curso_online_api
    restart: "no"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sistema_gestao_curso_online_client
    restart: "no"
    ports:
      - "80:3000"

  db:
    image: mysql:8.0
    container_name: sistema_gestao_curso_online_database
    restart: "no"
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data:
